# Generated by Django 4.1.2 on 2024-07-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_remove_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='autor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(default='categoria', max_length=50),
            preserve_default=False,
        ),
    ]
