# Generated by Django 4.1.2 on 2024-07-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='idAutor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('nacionalidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='idLibro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('año_publicacion', models.DateField()),
                ('descripcion_breve', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id_navItem', models.AutoField(db_column='idNavItem', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
