# Generated by Django 4.1.2 on 2024-07-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
