# Generated by Django 4.1.2 on 2024-07-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_libro_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.CharField(default='asd', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion_breve',
            field=models.CharField(blank=True, default='Sin descripción', max_length=500),
        ),
    ]
